name: Deploy FastAPI Scrapper to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd fastapi-scrapper
            # Use fast-forward only to avoid merge conflicts
            git pull --ff-only origin main
            # Restart Docker containers with sudo permissions
            sudo docker compose down
            sudo docker compose build
            sudo docker compose up -d --remove-orphans
          EOF
